### PR TITLE
minor typos in the main doc file

### PR DESCRIPTION
**Pull request by angea**

### CODE REVIEW

**Comment by thaidn** [comment]
Thanks angea! The PR looks good to me. Have you signed our CLA at https://cla.developers.google.com/?

Cheers :)

**Comment by Kcchouette** [comment]
There're also minor typos in the README:

```
69c69
< Our first set of tests are written in Java, because Java has a common
---
> Our first sets of tests are written in Java, because Java has a common
87c87
< sizes. Otherwise you'll see a lot of "iilegal key size" exceptions.
---
> sizes. Otherwise you'll see a lot of "illegal key size" exceptions.
175c175
< join, simply send an empty mail to wycheproof-users+subscribe@googlegroups.com.
---
> join, simply send an empty mail to wycheproof-users+subscribe@googlegroups.com.
\ No newline at end of file
```

**Comment by thaidn** [comment]
Thank you Kcchouette.

We're going to fix these typos in our internal repo and sync with GitHub after the holidays.

**Comment by Kcchouette** [comment]
@thaidn you forget that changes: https://github.com/google/wycheproof/pull/1#issuecomment-268765400

**Comment by thaidn** [comment]
Working on that. Can you send me a PR please?

Also "Our first sets of tests" seems not right. I think our current version is correct, at least according to Google stats:

https://www.google.com/search?q=%22Our+first+sets+of+tests%22&rlz=1CAZZAD_enUS718US729&oq=%22Our+first+sets+of+tests%22&aqs=chrome..69i57.1573j0j1&sourceid=chrome&ie=UTF-8#q=%22Our+first+sets+of%22: 12,300 results.

https://www.google.com/search?q=%22Our+first+sets+of+tests%22&rlz=1CAZZAD_enUS718US729&oq=%22Our+first+sets+of+tests%22&aqs=chrome..69i57.1573j0j1&sourceid=chrome&ie=UTF-8#q=%22Our+first+set+of%22: 338,000 results.

**Pull request merged**
