### PR TITLE
Add a tag of @Test in AesEaxTest.java

### PR DESCRIPTION
**Pull request by wwjd228**
Add a tag of @Test in AesEaxTest.java to avoid the test error.

### CODE REVIEW

**Comment by wwjd228** [comment]
> please reply here

I signed it !

**Comment by wwjd228** [comment]
> add another comment
I am the commit author.

**Comment by wwjd228** [comment]
> please reply here

I signed it !

**Comment by wwjd228** [comment]
> add another comment

I correct the email address.

**Comment by thaidn** [comment]
Thanks!

**Pull request merged**
